<?php
namespace Molajo\Tests;

use Molajo\User\Type\Public;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 11:36:55.
 */
class PublicTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Public
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $action         = '';
        $user_type = 'UserType1';
        $options        = array();

        $this->object = new Public($action, $user_type, $options);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Molajo\User\Type\Public::initialise
     * @todo   Implement testInitialise().
     */
    public function testInitialise()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::process
     * @todo   Implement testProcess().
     */
    public function testProcess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::setAction
     * @todo   Implement testSetAction().
     */
    public function testSetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::getAction
     * @todo   Implement testGetAction().
     */
    public function testGetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::setUserType
     * @todo   Implement testSetUserType().
     */
    public function testSetUserType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::getUserType
     * @todo   Implement testGetUserType().
     */
    public function testGetUserType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\Public::getOptions
     * @todo   Implement testGetOptions().
     */
    public function testGetOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
