<?php
namespace Molajo\Tests;

use Molajo\User\Cookies\Cookies;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 11:54:00.
 */
class UserCookiesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var $cookiesClass
     */
    protected $cookiesClass;

    /**
     * @covers Molajo\User\Cookies\Cookies::exists
     * @todo   Implement testInitialise().
     */
    public function setUp()
    {
        $class = 'Molajo\\User\\Cookies\\Cookies';
        $this->cookiesClass = new $class;

        return;
    }
    /**
     * @covers Molajo\User\Cookies\Cookies::exists
     */
    public function testSet()
    {
        $parameters = array();

        $expire = 60 * 60 * 60;
        $parameters['expire'] = time() + $expire;

        $path = '';
        $parameters['path'] = $path;

        $domain = '';
        $parameters['domain'] = $domain;

        $secure = 0;
        $parameters['secure'] = $secure;

        $httponly = 0;
        $parameters['httponly'] = $httponly;

        $key = 'MolajoCookie';
        $value = 'Toothpick';

        $set = $this->cookiesClass->set($key, $value, $parameters);
        var_dump($set);
        die;

        $this->assertEquals($set, $set);
    }


    /**
     * @covers Molajo\User\Cookies\Cookies::testSet
     */
    public function testSet()
    {
        $parameters = array();

        $expire = 60 * 60 * 60;
        $parameters['expire'] = time() + $expire;

        $path = '';
        $parameters['path'] = $path;

        $domain = '';
        $parameters['domain'] = $domain;

        $secure = 0;
        $parameters['secure'] = $secure;

        $httponly = 0;
        $parameters['httponly'] = $httponly;

        $key = 'MolajoCookie';
        $value = 'Toothpick';

        $set = $this->cookiesClass->set($key, $value, $parameters);

        $this->assertEquals($set, $set);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
