<?php
namespace Molajo\Tests;

use Molajo\User\User;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-17 at 11:54:00.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var UserType1
     */
    protected $object;

    /**
     * Setup testing
     */
    protected function setUp()
    {
    }

    /**
     * @covers Molajo\User\Cookies\Cookies::
     * @todo   Implement testInitialise().
     */
    public function testInitialise()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\UserType1::process
     * @todo   Implement testProcess().
     */
    public function testExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Molajo\User\Type\UserType1::close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

}
